// Mocks generated by Mockito 5.0.7 from annotations
// in criptan_code_test/test/ui/home/provider/home_provider_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:criptan_code_test/domain/model/character.dart' as _i4;
import 'package:criptan_code_test/domain/repository/item_repository_i.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [ItemRepositoryI].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemRepositoryI extends _i1.Mock implements _i2.ItemRepositoryI {
  MockItemRepositoryI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.AmongUsCharacter>> getCharacters() => (super.noSuchMethod(
      Invocation.method(#getCharacters, []),
      returnValue: Future<List<_i4.AmongUsCharacter>>.value(
          <_i4.AmongUsCharacter>[])) as _i3.Future<List<_i4.AmongUsCharacter>>);
}
